### ISSUE TITLE
Neue Posts werden nicht richtig erfasst

### ISSUE THREAD

**Issue by Jeremy-Hill-02** [stefanluth/kummerkasten#11]
https://github.com/stefanluth/kummerkasten/assets/88316345/e5f19584-b247-4f94-b19f-7551a2927038

Nach Erstellung von einem Post wird dieser beim Filtern nach Posts innerhalb der letzen 24h usw. nicht angezeigt.
Außerdem können diese Posts nach einem Klick auf den Home Button wieder gevoted werden, obwohl der Fingerprint sich nicht verändert haben sollte.

Der Fehler lässt sich durch einen Page-Reload beheben (zumindest das Filtern funktioniert wieder wie erwartet).
Daher gehe ich von einem Fehler beim Routing aus.

**Comment by stefanluth** [comment]
Scheint ein Bug zu sein
 https://github.com/vercel/next.js/issues/49450
