### ISSUE TITLE
Gemeldete Posts verstecken

### ISSUE THREAD

**Issue by stefanluth** [stefanluth/kummerkasten#6]
Posts die 10x gemeldet wurden (genaue Zahl diskutabel & konfigurierbar) sollen nicht gelöscht, sondern versteckt werden.

Es soll eine zusätzliche Seite geben, die diese Posts anzeigt, ggf. mit entsprechender Warnung, dass diese gemeldet wurden.

**Comment by Jeremy-Hill-02** [comment]
Ich würde die Anzahl auf 3 reduzieren. In der Praxis ist es eher unwahrscheinlich, dass jemals 10 Meldungen für einen Posts reinkommen tbh
